version: '2'
services:
    napchart-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/NapChart/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=NapChart
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
